import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Privacy Policy | Personal Memory API',
  description: 'Privacy policy for the Personal Memory API and GPT action.'
};

const sectionStyle = {
  marginTop: 28
};

const headingStyle = {
  fontSize: 22,
  margin: '0 0 10px'
};

const paragraphStyle = {
  color: '#374151',
  lineHeight: 1.7,
  margin: '0 0 12px'
};

export default function PrivacyPage() {
  return (
    <main
      style={{
        margin: '0 auto',
        maxWidth: 820,
        padding: '56px 20px'
      }}
    >
      <h1 style={{ fontSize: 40, lineHeight: 1.1, margin: '0 0 12px' }}>
        Privacy Policy
      </h1>
      <p style={{ ...paragraphStyle, color: '#6b7280' }}>
        Last updated: June 16, 2026
      </p>

      <section style={sectionStyle}>
        <h2 style={headingStyle}>Overview</h2>
        <p style={paragraphStyle}>
          Personal Memory API is a private memory storage service. It allows an
          authorized user or connected GPT action to save, search, retrieve,
          update, and delete user-provided memory entries.
        </p>
      </section>

      <section style={sectionStyle}>
        <h2 style={headingStyle}>Information We Process</h2>
        <p style={paragraphStyle}>
          The service processes memory content that you choose to submit,
          including titles, memory text, categories, tags, source labels, and
          timestamps. API requests may also include technical information such
          as request headers and server logs generated by the hosting provider.
        </p>
      </section>

      <section style={sectionStyle}>
        <h2 style={headingStyle}>How Information Is Used</h2>
        <p style={paragraphStyle}>
          Submitted memories are used only to provide the memory app functions:
          saving memories, listing recent memories, searching memories,
          retrieving memory details, updating memories, and deleting memories.
        </p>
      </section>

      <section style={sectionStyle}>
        <h2 style={headingStyle}>Storage and Security</h2>
        <p style={paragraphStyle}>
          Memory data is stored in MongoDB. The API endpoints are currently open
          for direct app and automation access, so avoid sending information you
          do not want stored in this service.
        </p>
      </section>

      <section style={sectionStyle}>
        <h2 style={headingStyle}>Sharing</h2>
        <p style={paragraphStyle}>
          This service does not sell memory data. Data is shared only with the
          infrastructure providers needed to operate the service, such as the
          application hosting provider and database provider.
        </p>
      </section>

      <section style={sectionStyle}>
        <h2 style={headingStyle}>Data Deletion</h2>
        <p style={paragraphStyle}>
          Memories can be deleted through the API using the delete memory
          endpoint. Deleted memories are removed from the application database,
          subject to any temporary backups or logs maintained by infrastructure
          providers.
        </p>
      </section>

      <section style={sectionStyle}>
        <h2 style={headingStyle}>GPT Action Use</h2>
        <p style={paragraphStyle}>
          If this API is connected to a Custom GPT action, the GPT may send
          requests to this service only when the action is invoked. The API key
          is used to authorize those requests.
        </p>
      </section>

      <section style={sectionStyle}>
        <h2 style={headingStyle}>Contact</h2>
        <p style={paragraphStyle}>
          For privacy questions, contact the owner or administrator of this
          Personal Memory API deployment.
        </p>
      </section>
    </main>
  );
}
